#!/bin/bash
set -euo pipefail

if [[ "${BUILDKITE_PLUGIN_RSYNC_DEBUG:-false}" =~ (true|on|1) ]] ; then
  echo "--- :hammer: Enabling debug mode"
  set -x
fi

paths=()

if [[ -n "${BUILDKITE_PLUGIN_RSYNC_POST:-}" ]] ; then
  paths+=("$BUILDKITE_PLUGIN_RSYNC_POST")
fi

while IFS='=' read -r path _ ; do
  if [[ $path =~ ^(BUILDKITE_PLUGIN_RSYNC_POST_[0-9]+) ]] ; then
    paths+=("${!path}")
  fi
done < <(env | sort)

workdir=${BUILDKITE_PLUGIN_RSYNC_WORKDIR:-.}

pushd "${workdir}"
trap popd EXIT

echo "--- rsync-ing "

for path in "${paths[@]}"
  do
    ## `eval` to support step-time varibles in the command
    eval rsync $path
  done
